// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { Turn, TurnTableId } from "./tables/Turn.sol";
import { GameStartTime, GameStartTimeTableId } from "./tables/GameStartTime.sol";
import { GameIsLive, GameIsLiveTableId } from "./tables/GameIsLive.sol";
import { Username, UsernameTableId } from "./tables/Username.sol";
import { Champion, ChampionTableId } from "./tables/Champion.sol";
import { Movable, MovableTableId } from "./tables/Movable.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Alive, AliveTableId } from "./tables/Alive.sol";
import { Health, HealthTableId } from "./tables/Health.sol";
import { Range, RangeTableId } from "./tables/Range.sol";
import { ActionPoint, ActionPointTableId } from "./tables/ActionPoint.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { ActivityLog, ActivityLogTableId } from "./tables/ActivityLog.sol";
import { MoveExecuted, MoveExecutedData, MoveExecutedTableId } from "./tables/MoveExecuted.sol";
import { GameStarted, GameStartedTableId } from "./tables/GameStarted.sol";
import { GameEnded, GameEndedTableId } from "./tables/GameEnded.sol";
