// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { GameSession, GameSessionData, GameSessionTableId } from "./tables/GameSession.sol";
import { ClaimInterval, ClaimIntervalTableId } from "./tables/ClaimInterval.sol";
import { Username, UsernameTableId } from "./tables/Username.sol";
import { Champion, ChampionTableId } from "./tables/Champion.sol";
import { Movable, MovableTableId } from "./tables/Movable.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Alive, AliveTableId } from "./tables/Alive.sol";
import { Health, HealthTableId } from "./tables/Health.sol";
import { Range, RangeTableId } from "./tables/Range.sol";
import { InGame, InGameTableId } from "./tables/InGame.sol";
import { LastActionPointClaim, LastActionPointClaimTableId } from "./tables/LastActionPointClaim.sol";
import { LastVotingPointClaim, LastVotingPointClaimTableId } from "./tables/LastVotingPointClaim.sol";
import { ActionPoint, ActionPointTableId } from "./tables/ActionPoint.sol";
import { VotingPoint, VotingPointTableId } from "./tables/VotingPoint.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { PlayerSpawned, PlayerSpawnedData, PlayerSpawnedTableId } from "./tables/PlayerSpawned.sol";
import { MoveExecuted, MoveExecutedData, MoveExecutedTableId } from "./tables/MoveExecuted.sol";
import { AttackExecuted, AttackExecutedData, AttackExecutedTableId } from "./tables/AttackExecuted.sol";
import { SendActionPointExecuted, SendActionPointExecutedData, SendActionPointExecutedTableId } from "./tables/SendActionPointExecuted.sol";
import { RangeIncreaseExecuted, RangeIncreaseExecutedData, RangeIncreaseExecutedTableId } from "./tables/RangeIncreaseExecuted.sol";
import { ActionPointClaimExecuted, ActionPointClaimExecutedData, ActionPointClaimExecutedTableId } from "./tables/ActionPointClaimExecuted.sol";
import { ClaimExecuted, ClaimExecutedData, ClaimExecutedTableId } from "./tables/ClaimExecuted.sol";
import { VotingPointClaimExecuted, VotingPointClaimExecutedData, VotingPointClaimExecutedTableId } from "./tables/VotingPointClaimExecuted.sol";
import { VoteExecuted, VoteExecutedData, VoteExecutedTableId } from "./tables/VoteExecuted.sol";
import { GameStarted, GameStartedData, GameStartedTableId } from "./tables/GameStarted.sol";
import { GameEnded, GameEndedTableId } from "./tables/GameEnded.sol";
