// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMapSystem {
  function spawn(string memory username) external;

  function move(uint256 timestamp, uint32 x, uint32 y) external;
}
