// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITurnSystem {
  function startMatch(uint32 playersSpawned, uint256 startTime) external;

  function incrementTurn() external;

  function increaseRange() external;

  function sendActionPoint(bytes32 _recipient) external;

  function attackPlayer(bytes32 _target) external;
}
