// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITurnSystem {
  function startMatch(uint256 gameId, uint32 playersSpawned, uint256 startTime) external;

  function incrementTurn() external;

  function increaseRange(uint256 timestamp) external;

  function sendActionPoint(uint256 timestamp, bytes32 _recipient) external;

  function attackPlayer(uint256 timestamp, bytes32 _target) external;

  function claimActionPoint(uint256 timestamp) external;

  function claimVotingPoint(uint256 timestamp) external;

  function vote(uint256 timestamp, bytes32 _recipient) external;
}
